[package]
name = "algcmp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.59"
clap-verbosity-flag = "3.0.4"
env_logger = "0.11.9"
futures = "0.3.32"
log = "0.4.29"
regex = "1.12.3"
reqwest = "0.13.2"
thiserror = "2.0.18"
tokio = "1.49.0"
